import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";
import { AppSidebar } from "@/components/layout/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className={`flex h-screen w-screen bg-gray-100 text-gray-900`}>
          <AppSidebar />
          <main className="flex-1">{children}</main>
      </div>
  );
}
